@EcommerceDev_API_HostAddress = http://localhost:5020
@customerId = 12c76662-2323-4e7e-a53e-0ea257bc1233
@addressId = 416e1549-c8c5-4b71-be87-4caecf113f1b
@categoryId = 47cadc2b-4168-489b-99a1-e4057f465060
@productId = 8d9405e9-91e8-4685-9167-9ab53d136947
@zipCode  = 05001-200

###

POST {{EcommerceDev_API_HostAddress}}/api/customers
Content-Type: application/json

{
  "fullName": "Lucas Woibau",
  "email": "lucaswoibau7@gmail.com",
  "phone": "12345678910",
  "birthDate": "2001-02-17",
  "document": "123321"
}

###

POST {{EcommerceDev_API_HostAddress}}/api/customers/{{customerId}}/addresses
Content-Type: application/json

{
  "idCustomer": "07d762f1-f424-4c87-891c-0b031b0afdac",
  "recipientName": "Lucas Maciel Woibau",
  "addressLine1": "Rua das Flores, 123",
  "addressLine2": "Apto 201",
  "zipCode": "29750-000",
  "district": "Centro",
  "state": "ES",
  "country": "Brasil",
  "city": "Pancas"
}

###

POST {{EcommerceDev_API_HostAddress}}/api/customers
Content-Type: application/json
{
  "Title": "Tecnologia",
  "Subcategory": "Computador"
}

###

POST {{EcommerceDev_API_HostAddress}}/api/products
Content-Type: application/json
{
  "title": "Tecnologia",
  "description": "Computador",
  "price": 5000,
  "brand": "Avell",
  "quantity": 5,
  "idCategory": "{{categoryId}}"
}

###

POST {{EcommerceDev_API_HostAddress}}/api/orders
Content-Type: application/json
{
  "idCustomer": "{{customerId}}",
  "items": [
    {
      "idProduct": "{{productId}}",
      "quantity": 1
    },
    {
      "idProduct": "9188e8b1-ebfa-4390-b700-997510309ef1",
      "quantity": 3
    }
  ],
  "deliveryAddressId": "{{addressId}}",
}

###

PUT {{EcommerceDev_API_HostAddress}}/api/shopping-carts/{{customerId}}
Content-Type: application/json
{
  "items": [
    {
      "idProduct": "{{productId}}",
      "quantity": 4
    },
  ]
}

###

GET  {{EcommerceDev_API_HostAddress}}/api/shopping-carts/{{customerId}}

###

POST {{EcommerceDev_API_HostAddress}}/api/orders/calculate-shipping
Content-Type: application/json
{
  "zipCode": "{{zipCode}}",
  "items": [
    {
      "idProduct": "{{productId}}",
      "quantity": 1
    },
    {
      "idProduct":"9188e8b1-ebfa-4390-b700-997510309ef1",
      "quantity": 2
    }
  ]
}